apiVersion: v1
kind: Service
metadata:
  name: nodejs-front-end
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: nodejs-front-end
