apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejs-front-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nodejs-front-end
        microservice: nodejs-front-end
        environment: dev
        kubernetes-service: nodejs-front-end
    spec:
      containers:
      - name: nodejs-front-end
        image: adopdemointernal.azurecr.io/adopdemointernal/nodejs-front-end:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
